### ISSUE TITLE
i am dumb

### ISSUE THREAD

**Issue by KRIEZIEY** [De-eloper/NjRat-0.7d-Horror-Edition#2]
Do i need open ports to use this?

**Comment by De-eloper** [comment]
yes you need to open port in router, but if that not possible you can do methods.
i recommend ngrok.com if you want to use pastebin, you have to keep editing the pastebin to get the victims
or more permanent you can use playit.gg or packetriot.com to open ports
good luck

**Comment by KRIEZIEY** [comment]
can u pls make a mini guide how to open ports by ngrok.com

**Comment by KRIEZIEY** [comment]
thank you

**Comment by De-eloper** [comment]
no problem bro 👍👍
