### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by KRIEZIEY** [De-eloper/NjRat-0.7d-Horror-Edition#3]
Pls add some features: sound to screamers, vieuw clipboard, win locker, kill browser.

**Comment by De-eloper** [comment]
thanks for suggesting features, I can attempt to add these features in time, i will think of implementing them but it takes a while and i'll try add them one by one.
1. sound of screamers (it uses exe from plugin folder, i originally had sound before. i can re-add a screamer sound)
2. viewing clipboard (if i figure out how to send and receive message proper in rat i can implement this, i have to figure it in some whiles. or it would be poorly implement like admin check only sends to logs)
3. win locker (might be possible but i cannot add forms into the stub or it never compiles from njrat builder, so i might implement a simple transparent locker overlay like njrat lime edition does)
4. kill browser (i have this feature in the fun section, but that does not loop in a timer and uses taskill currently, i think i can add a toggle for killing browser in a loop on and off toggler, i can probably add it)

**Comment by De-eloper** [comment]
this was old plugins, you can replace all the screamer in plugins folder of nj horror with them, if you want different sound effect i can change
[Screamer Plugin With Sound.zip](https://github.com/De-eloper/NjRat-0.7d-Horror-Edition/files/9768080/Screamer.Plugin.With.Sound.zip)

**Comment by De-eloper** [comment]
i have been busy lately, but now i have time to trying adding features again,
scremaer now has loud sound effect, turn down volume if you try on your own pc.
i added a screen locker (lock and unlock) cannot be killed even  by alt + f4, taskmgr, can only go away on restarting pc. check releases

**Comment by De-eloper** [comment]
All freatures added bro, check newest upload. if there is any bugs or if you want me to try improve it, give reply

**Comment by KRIEZIEY** [comment]
thank you v much

**Comment by De-eloper** [comment]
the clipboard before was poorly implemented, i have updated so it works 100% better. check update if you need it. new ui:
![clpp](https://user-images.githubusercontent.com/113988354/195946750-ed9a94ef-96ff-43f7-87c2-78989d2ab376.PNG)
